tap thoughtbot/formulae

install git
install git-extras
install hub
install id3v2
install imagemagick
install irssi
install libxml2
install macvim
install media-info
install mongodb
install mp3check
install mp3info
install mplayer
install mysql
install node
install postgresql
install python
install rbenv-default-gems
install rbenv-gemset
install rcm
install redis
install rename
install taglib
install the_silver_searcher
install tig
install tmux
install vim
install wget
install youtube-dl
install zsh-completions

tap mpv-player/mpv
install --with-bundle --HEAD mpv

tap phinze/cask

linkapps
cleanup
